### ISSUE TITLE
PCB Sizing Wrong

### ISSUE THREAD

**Issue by KyleMay** [squix78/esp8266-fritzing-parts#2]
The sizing for PCB is incorrect: too wide and pin spacing is too far apart.

**Comment by rayzor187** [comment]
Is there any plans on fixing the faulty PCB size?

**Comment by holymoly** [comment]
Just want to correct my Issue. The size is not wrong. There are different types out there. A small one and a big one. This layout is not 100% perfect. I just made 2 of these. The holes i made are to small and the 2,54mm spacing is not perfect. 
Will update later

**Comment by skwashd** [comment]
@squix78 this can be closed as it was fixed in PR #3.
